version: '3'

services:

  microservice_1:
    image: etl_data_pipeline
    build: 
      context: ./microservice_1
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    restart: always

  microservice_2:
    image: data_storage
    build: 
      context: ./microservice_2
      dockerfile: Dockerfile
    ports:
      - 9001:9000
    restart: always
