version: '3'

services:

  service_1:
    image: etl_data_pipeline
    build: 
      context: ./service_1
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    restart: always

  service_2:
    image: servizio_2
    build: 
      context: ./service_2
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    restart: always
