version: '3'

networks:
  default:
    name: dsbd_private_network
    driver: bridge

services:

  microservice_1:
    image: etl_data_pipeline
    container_name: etl_data_pipeline_container
    build: 
      context: ./microservice_1
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    restart: always

  microservice_2:
    image: data_storage
    container_name: data_storage_container
    build: 
      context: ./microservice_2
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      PYTHONUNBUFFERED: 1

  microservice_3:
    image: data_retrieval
    container_name: data_retrieval_container
    build: 
      context: ./microservice_3
      dockerfile: Dockerfile
    ports:
      - 9003:9000
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      PYTHONUNBUFFERED: 1

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      #MYSQL_USER: user
      #MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3306"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080