version: '3'

services:

  microservice_1:
    image: etl_data_pipeline
    build: 
      context: ./microservice_1
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    restart: always

  microservice_2:
    image: data_storage
    build: 
      context: ./microservice_2
      dockerfile: Dockerfile
    restart: always
    command: --default-authentication-plugin=mysql_native_password #da spostare nel dockerfile se possibile

  microservice_3:
    image: data_retrieval
    build: 
      context: ./microservice_3
      dockerfile: Dockerfile
    ports:
      - 9003:9000
    restart: always
    environment:
      - DATA_STORAGE_HOST=microservice_2

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080