version: '3'

services:

  microservice_1:
    image: etl_data_pipeline
    build: 
      context: ./microservice_1
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    restart: always

  microservice_2:
    image: data_storage
    build: 
      context: ./microservice_2
      dockerfile: Dockerfile
    restart: always
    command: --default-authentication-plugin=mysql_native_password #da spostare nel dockerfile se possibile

  microservice_3:
    image: data_retrieval
    build: 
      context: ./microservice_3
      dockerfile: Dockerfile
    ports:
      - 9003:9000
    restart: always
    environment:
      - DATA_STORAGE_HOST=microservice_2

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080