version: '3'

services:

  microservice_1:
    image: etl_data_pipeline
    container_name: etl_data_pipeline_container
    build: 
      context: ./microservice_1
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    restart: always

  microservice_2:
    image: data_storage
    container_name: data_storage_container
    build: 
      context: ./microservice_2
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql

  microservice_3:
    image: data_retrieval
    container_name: data_retrieval_container
    build: 
      context: ./microservice_3
      dockerfile: Dockerfile
    ports:
      - 9003:9000
    restart: always
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      ## MYSQL_USER : user
      ## MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080