# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\"\x15\n\x13getAllMetricsParams\"\x1c\n\nAllMetrics\x12\x0e\n\x06result\x18\x01 \x01(\t2M\n\x0b\x45\x63hoService\x12>\n\rgetAllMetrics\x12\x19.echo.getAllMetricsParams\x1a\x10.echo.AllMetrics\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETALLMETRICSPARAMS._serialized_start=20
  _GETALLMETRICSPARAMS._serialized_end=41
  _ALLMETRICS._serialized_start=43
  _ALLMETRICS._serialized_end=71
  _ECHOSERVICE._serialized_start=73
  _ECHOSERVICE._serialized_end=150
# @@protoc_insertion_point(module_scope)
