# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import echo_pb2 as echo__pb2


class EchoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendStats = channel.unary_unary(
                '/echo.EchoService/sendStats',
                request_serializer=echo__pb2.statsNameParam.SerializeToString,
                response_deserializer=echo__pb2.resultValue.FromString,
                )
        self.sendMetrics = channel.unary_unary(
                '/echo.EchoService/sendMetrics',
                request_serializer=echo__pb2.statsNameParam.SerializeToString,
                response_deserializer=echo__pb2.resultValue.FromString,
                )
        self.getNumberOfViolationsPast = channel.unary_unary(
                '/echo.EchoService/getNumberOfViolationsPast',
                request_serializer=echo__pb2.listMetricsParam.SerializeToString,
                response_deserializer=echo__pb2.resultValue.FromString,
                )
        self.getNumberOfViolationsFuture = channel.unary_unary(
                '/echo.EchoService/getNumberOfViolationsFuture',
                request_serializer=echo__pb2.listMetricsParam.SerializeToString,
                response_deserializer=echo__pb2.resultValue.FromString,
                )


class EchoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getNumberOfViolationsPast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getNumberOfViolationsFuture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendStats': grpc.unary_unary_rpc_method_handler(
                    servicer.sendStats,
                    request_deserializer=echo__pb2.statsNameParam.FromString,
                    response_serializer=echo__pb2.resultValue.SerializeToString,
            ),
            'sendMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.sendMetrics,
                    request_deserializer=echo__pb2.statsNameParam.FromString,
                    response_serializer=echo__pb2.resultValue.SerializeToString,
            ),
            'getNumberOfViolationsPast': grpc.unary_unary_rpc_method_handler(
                    servicer.getNumberOfViolationsPast,
                    request_deserializer=echo__pb2.listMetricsParam.FromString,
                    response_serializer=echo__pb2.resultValue.SerializeToString,
            ),
            'getNumberOfViolationsFuture': grpc.unary_unary_rpc_method_handler(
                    servicer.getNumberOfViolationsFuture,
                    request_deserializer=echo__pb2.listMetricsParam.FromString,
                    response_serializer=echo__pb2.resultValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.EchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EchoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/sendStats',
            echo__pb2.statsNameParam.SerializeToString,
            echo__pb2.resultValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/sendMetrics',
            echo__pb2.statsNameParam.SerializeToString,
            echo__pb2.resultValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getNumberOfViolationsPast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/getNumberOfViolationsPast',
            echo__pb2.listMetricsParam.SerializeToString,
            echo__pb2.resultValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getNumberOfViolationsFuture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/getNumberOfViolationsFuture',
            echo__pb2.listMetricsParam.SerializeToString,
            echo__pb2.resultValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
