FROM confluentinc/cp-kafka:latest
# kafka-topics --create --topic prova --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3
CMD ["kafka-topics", "--create" "--topic", "prova" ,"--bootstrap-server", "kafka:9092", "--replication-factor", "1", "--partitions", "3" ]