# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import echo_pb2 as echo__pb2


class EchoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAllMetrics = channel.unary_unary(
                '/echo.EchoService/getAllMetrics',
                request_serializer=echo__pb2.emptyParam.SerializeToString,
                response_deserializer=echo__pb2.resultValue.FromString,
                )
        self.getMetadataForMetrics = channel.unary_unary(
                '/echo.EchoService/getMetadataForMetrics',
                request_serializer=echo__pb2.idMetricParam.SerializeToString,
                response_deserializer=echo__pb2.resultValue.FromString,
                )
        self.getHistoryForMetrics = channel.unary_unary(
                '/echo.EchoService/getHistoryForMetrics',
                request_serializer=echo__pb2.idMetricParam.SerializeToString,
                response_deserializer=echo__pb2.resultValue.FromString,
                )


class EchoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getAllMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMetadataForMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getHistoryForMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getAllMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.getAllMetrics,
                    request_deserializer=echo__pb2.emptyParam.FromString,
                    response_serializer=echo__pb2.resultValue.SerializeToString,
            ),
            'getMetadataForMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.getMetadataForMetrics,
                    request_deserializer=echo__pb2.idMetricParam.FromString,
                    response_serializer=echo__pb2.resultValue.SerializeToString,
            ),
            'getHistoryForMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.getHistoryForMetrics,
                    request_deserializer=echo__pb2.idMetricParam.FromString,
                    response_serializer=echo__pb2.resultValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.EchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EchoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getAllMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/getAllMetrics',
            echo__pb2.emptyParam.SerializeToString,
            echo__pb2.resultValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMetadataForMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/getMetadataForMetrics',
            echo__pb2.idMetricParam.SerializeToString,
            echo__pb2.resultValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getHistoryForMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/getHistoryForMetrics',
            echo__pb2.idMetricParam.SerializeToString,
            echo__pb2.resultValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
